#!/usr/bin/env node
/**
 * Copy the web app's bundled MP3s into the native app and generate the
 * native audio registry.
 *
 *   npm run export-audio          (from mobile/; needs no root install)
 *
 * What it writes
 * --------------
 * - `assets/audio/greet/*.mp3`   `public/assets/audio/greet/*.mp3`
 * - `assets/audio/hub/*.mp3`     `public/assets/audio/hub/*.mp3`
 * - `assets/audio/path/*.mp3`    `public/assets/audio/path/*.mp3` (Emma's
 *                                Path + guidance lines)
 * - `assets/audio/sfx/*.mp3`     `public/assets/sfx-*.mp3`
 * - `src/audio/audioRegistry.ts` web URL path → `require()`d native module
 *
 * The files are copied byte for byte: the web's voice-QA page is the ear
 * gate for every clip, so the native app must play the same bytes.
 * `src/audio/audioRegistry.test.ts` fails when a copy drifts from its web
 * original or a manifest line has no copy, i.e. whenever a web re-render
 * lands without a re-run of this script.
 */
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const mobileRoot = resolve(here, '..')
const repoRoot = resolve(mobileRoot, '..')
const webAssets = join(repoRoot, 'public', 'assets')
const out = join(mobileRoot, 'assets', 'audio')

/** [web dir, web URL prefix, file filter, native subdir] */
const GROUPS = [
  [
    join(webAssets, 'audio', 'greet'),
    '/assets/audio/greet/',
    /\.mp3$/,
    'greet',
  ],
  [join(webAssets, 'audio', 'hub'), '/assets/audio/hub/', /\.mp3$/, 'hub'],
  [join(webAssets, 'audio', 'path'), '/assets/audio/path/', /\.mp3$/, 'path'],
  [webAssets, '/assets/', /^sfx-.*\.mp3$/, 'sfx'],
]

const entries = []
for (const [webDir, urlPrefix, filter, subdir] of GROUPS) {
  const dest = join(out, subdir)
  rmSync(dest, { recursive: true, force: true })
  mkdirSync(dest, { recursive: true })
  const files = readdirSync(webDir)
    .filter((f) => filter.test(f))
    .sort()
  for (const file of files) {
    copyFileSync(join(webDir, file), join(dest, file))
    entries.push([
      `${urlPrefix}${file}`,
      `../../assets/audio/${subdir}/${file}`,
    ])
  }
  console.log(`${subdir}: ${files.length} files`)
}

entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
const lines = entries.map(([url, path]) => `  '${url}': require('${path}'),`)
const source = `/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * GENERATED by \`mobile/scripts/export-audio.mjs\`. Do not edit by hand:
 * re-run \`npm run export-audio\` after a web MP3 changes.
 *
 * Web URL path (what core's line manifests and the web screens use) → the
 * bundled native audio module. Look clips up through \`./bundledAudio.ts\`.
 */
export const WEB_AUDIO_MODULES: Readonly<Record<string, number>> = {
${lines.join('\n')}
}
`
writeFileSync(join(mobileRoot, 'src', 'audio', 'audioRegistry.ts'), source)
console.log(`registry: ${entries.length} entries`)
